### PR TITLE
Adding new user Tim Wells

### PR DESCRIPTION
**Pull request by Dale-iohk**
* Project to be added to: Identus
* Team to be added to: Identus-maintainers

### CODE REVIEW

**Comment by ryjones** [comment]
Hi @Dale-iohk - you need to rebase on main, and do a `git commit --amend -s`

```
git rebase main
git commit --amend -s
git push origin --force-with-lease origin add-tim-wells
```

**Review by ryjones — CHANGES_REQUESTED** [review]
needs rebased and signed

**Comment by Dale-iohk** [comment]
Hi Ry, the example push command kicked back an error.

`governance % git rebase main
Current branch add-tim-wells is up to date.

governance % git commit --amend -s
[add-tim-wells fa2e929] Adding new user Tim Wells
 Date: Tue Jul 2 11:43:27 2024 -0700
 1 file changed, 2 insertions(+)

governance % git push origin --force-with-lease origin add-tim-wells
error: src refspec origin does not match any
error: failed to push some refs to 'https://github.com/Dale-iohk/governance.git'`

**Comment by ryjones** [comment]
Hi @Dale-iohk - you need to rebase on main because you are picking up an old commit.

**Review by yshyn-iohk — APPROVED** [review]

**Pull request merged**
